name: example
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  platform: ^3.0.2
  js: ^0.6.3
  built_value_generator: ^8.1.3
  mockito: ^5.0.16
  http: ^0.13.4
  jaguar_jwt: ^3.0.0
  dart_jsonwebtoken: ^2.4.0
  path_provider: ^1.6.27

dev_dependencies:
  build_runner: ^2.1.5

  flutter_test:
    sdk: flutter

flutter:
    assets: 
    - lib/test_data/example.json